// Northwind Cloud — mock data for the demo when USE_SDK is false (or the SDK
// widget is unavailable). Mirrors the design artifact's data.js.

export const mockData = {
  org: {
    name: "Northwind Cloud",
    slug: "northwind",
    plan: "Business",
    id: "org_01HZX9P4KQYG8WJTVH3M2N1",
    members: 142,
    domains: 3,
    region: "us-east-1",
    createdAt: "Aug 12, 2024",
  },
  orgs: [
    { id: "org_north", name: "Northwind Cloud", plan: "Business", color: "#1E5DDB" },
    { id: "org_acme", name: "Acme Pay", plan: "Enterprise", color: "#7c3aed" },
    { id: "org_glx", name: "Globex Logistics", plan: "Starter", color: "#0891b2" },
    { id: "org_init", name: "Initech", plan: "Business", color: "#16a34a" },
  ],
  currentUser: {
    name: "Aria Chen",
    email: "aria.chen@northwind.io",
    role: "Owner",
    initials: "AC",
  },
  users: [
    { name: "Aria Chen", email: "aria.chen@northwind.io", role: "Owner", roleId: "role_owner", status: "active", mfa: true, lastSeen: "Just now", initials: "AC", color: "#1E5DDB" },
    { name: "Marcus Wong", email: "marcus.w@northwind.io", role: "Admin", roleId: "role_admin", status: "active", mfa: true, lastSeen: "12 min ago", initials: "MW", color: "#7c3aed" },
    { name: "Priya Sharma", email: "priya.s@northwind.io", role: "Admin", roleId: "role_admin", status: "active", mfa: true, lastSeen: "1 hr ago", initials: "PS", color: "#db2777" },
    { name: "Lukas Becker", email: "l.becker@northwind.io", role: "Developer", roleId: "role_developer", status: "active", mfa: false, lastSeen: "3 hr ago", initials: "LB", color: "#16a34a" },
    { name: "Sara O'Brien", email: "sara.obrien@northwind.io", role: "Developer", roleId: "role_developer", status: "active", mfa: true, lastSeen: "Yesterday", initials: "SO", color: "#f59e0b" },
    { name: "Diego Alvarez", email: "diego@partner-axiom.com", role: "Billing", roleId: "role_billing", status: "active", mfa: true, lastSeen: "2 days ago", initials: "DA", color: "#0891b2" },
    { name: "Yuki Tanaka", email: "yuki.t@northwind.io", role: "Support", roleId: "role_support", status: "active", mfa: false, lastSeen: "4 days ago", initials: "YT", color: "#be123c" },
    { name: "—", email: "j.malone@northwind.io", role: "Developer", roleId: "role_developer", status: "invited", mfa: false, lastSeen: "—", initials: "JM", color: "#94a3b8" },
    { name: "—", email: "t.fischer@vendor-loop.com", role: "Viewer", roleId: "role_viewer", status: "invited", mfa: false, lastSeen: "—", initials: "TF", color: "#94a3b8" },
    { name: "Hana Kim", email: "hana@northwind.io", role: "Viewer", roleId: "role_viewer", status: "suspended", mfa: true, lastSeen: "3 weeks ago", initials: "HK", color: "#64748b" },
    { name: "—", email: "old.contractor@gmail.com", role: "Viewer", roleId: "role_viewer", status: "expired", mfa: false, lastSeen: "—", initials: "OC", color: "#cbd5e1" },
  ],
  roles: [
    { id: "role_owner", name: "Owner", description: "Full access — including billing and destruction", members: 1, type: "system" },
    { id: "role_admin", name: "Admin", description: "Manage users, roles, and security settings", members: 2, type: "system" },
    { id: "role_developer", name: "Developer", description: "Read/write app config, API keys, and SDK secrets", members: 3, type: "custom" },
    { id: "role_billing", name: "Billing", description: "View invoices, edit payment methods, manage seats", members: 1, type: "system" },
    { id: "role_support", name: "Support", description: "Read user profiles, resend invites, reset MFA", members: 1, type: "custom" },
    { id: "role_viewer", name: "Viewer", description: "Read-only access across the workspace", members: 3, type: "system" },
  ],
  invitations: [
    { email: "j.malone@northwind.io", role: "Developer", invitedBy: "Aria Chen", sentAt: "2 hours ago", expiresAt: "in 6 days", status: "pending" },
    { email: "t.fischer@vendor-loop.com", role: "Viewer", invitedBy: "Marcus Wong", sentAt: "Yesterday", expiresAt: "in 5 days", status: "pending" },
    { email: "amir.k@northwind.io", role: "Admin", invitedBy: "Aria Chen", sentAt: "3 days ago", expiresAt: "in 3 days", status: "pending" },
    { email: "noor.t@northwind.io", role: "Developer", invitedBy: "Priya Sharma", sentAt: "May 14", expiresAt: "Expired May 21", status: "expired" },
    { email: "ben.r@northwind.io", role: "Viewer", invitedBy: "Aria Chen", sentAt: "May 10", expiresAt: "Accepted May 11", status: "accepted" },
    { email: "kate.b@northwind.io", role: "Viewer", invitedBy: "Marcus Wong", sentAt: "May 8", expiresAt: "Accepted May 9", status: "accepted" },
    { email: "old.contractor@gmail.com", role: "Viewer", invitedBy: "Aria Chen", sentAt: "Apr 30", expiresAt: "Expired May 7", status: "expired" },
  ],
  domains: [
    { domain: "northwind.io", primary: true, status: "verified", verifiedAt: "Aug 12, 2024", autoJoin: true, ssoEnforced: true },
    { domain: "northwind.dev", primary: false, status: "verified", verifiedAt: "Jan 04, 2025", autoJoin: true, ssoEnforced: true },
    { domain: "northwind-eu.com", primary: false, status: "pending", verifiedAt: "—", autoJoin: false, ssoEnforced: false },
  ],
  activity: [
    { who: "Priya Sharma", what: "invited", target: "amir.k@northwind.io as Admin", tone: "blue", ago: "12 min ago" },
    { who: "Marcus Wong", what: "enabled", target: "MFA enforcement for all members", tone: "green", ago: "1 hour ago" },
    { who: "Aria Chen", what: "promoted", target: "Priya Sharma from Developer → Admin", tone: "blue", ago: "3 hours ago" },
    { who: "System", what: "rotated", target: "API signing key (next rotation in 87d)", tone: "amber", ago: "Yesterday" },
    { who: "Lukas Becker", what: "signed in via", target: "Google Workspace SSO", tone: "green", ago: "Yesterday" },
    { who: "Marcus Wong", what: "verified", target: "domain northwind.dev", tone: "green", ago: "2 days ago" },
    { who: "Aria Chen", what: "suspended", target: "Hana Kim", tone: "red", ago: "3 weeks ago" },
  ],
  permissions: [
    { cat: "Users", create: ["Owner","Admin"], read: ["Owner","Admin","Developer","Support","Viewer"], update: ["Owner","Admin"], delete: ["Owner"] },
    { cat: "Roles", create: ["Owner","Admin"], read: ["Owner","Admin","Developer","Support","Viewer"], update: ["Owner","Admin"], delete: ["Owner"] },
    { cat: "Connections", create: ["Owner","Admin"], read: ["Owner","Admin","Developer"], update: ["Owner","Admin"], delete: ["Owner"] },
    { cat: "API Keys", create: ["Owner","Admin","Developer"], read: ["Owner","Admin","Developer"], update: ["Owner","Admin","Developer"], delete: ["Owner","Admin"] },
    { cat: "Billing", create: ["Owner","Billing"], read: ["Owner","Billing"], update: ["Owner","Billing"], delete: ["Owner"] },
    { cat: "Audit Logs", create: [], read: ["Owner","Admin","Support"], update: [], delete: [] },
  ],
};
